### ISSUE TITLE
♻️🧹 Post 0.6.0 Cleanup

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#1002]
### Proposed refactoring

After the currently open PRs are merged I would like to do some refactoring before going on, 
The reason not to do them while we got open PRs is mainly to prevent merge conflicts since some changes might change a lot of files and the folder layout.

- [x] ♻️ Run sourcery on the whole code base #1000 
- [x] ♻️ Refactor test structure to use tests folder at repo root #969 
- [x] 🔧 Make mypy and doc string linters opt out instead of opt in #1001

### Benefits

- [x] Makes code easier to maintain
- [x] Improved readability of the code

**Comment by s-weigand** [comment]
Since `0.8.0` will be a rewrite let's postpone this.
