### ISSUE TITLE
Adjust to change on gh actions

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#247]
The TODO is migrated from #246 

## TODO
Sadly for the moment we will lose some convenience services:
- [x] **coveralls**: Atm the normal clients don't support actions and the action doesn't support the coverage output of `pytest-cov` ([see](https://github.com/coverallsapp/github-action/issues/15)).
- [x] **Slack integration**: The there are already [quite some slack action](https://github.com/marketplace?utf8=%E2%9C%93&type=actions&query=slack), 
I need to figure out which one to use and how to configure it. @joernweissenborn  I also need access to the secret slack token.
- [x] **Deployment**: The deployment is added to the actions, but for it to work @jsnel or I need to add our [PyPi token](https://pypi.org/help/#apitoken) to the `secrets` of the `glotaran/pyglotaran` repo.
- [x] **Deactivate good old travis and appveyor**

**Comment by joernweissenborn** [comment]
@s-weigand Your are Workspace Admin in slack

**Comment by joernweissenborn** [comment]
I guess this can be closed?

**Comment by s-weigand** [comment]
With the more or less pending change from slack to another platform, I'm not thaaaaaat motivated to get into configuring slack with gh action, but if you really want the 'CI is done with success/error' notification I can give it a try.

**Comment by jsnel** [comment]
This is already working. The Github bot passes through all notifications, including on the completion of Github actions. That looks like this:
![image](https://user-images.githubusercontent.com/3616369/70375842-02281900-1903-11ea-948c-af050b9b712f.png)
