### ISSUE TITLE
Recreate analysis from saved result 

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#316]
Currently, in version 0.0.16, the result object already holds a lot of information, but not enough to reconstruct the analysis that was performed to create the result in the first place. 

Users of the software would appreciate if the result object saved by pyglotaran would be fully self contained. In order to do so we would need to address the following issues:

- [ ] #317 Create model object from saved result object
- [ ] #318 Create parameter object from saved result object
- [ ] #320 Store parameters (initial and final) in saved result object
- [ ] #321 Store model type and irf type as part of saved result object

**Comment by joernweissenborn** [comment]
See #767 and #766
