### ISSUE TITLE
Checklist for merging staging into main

### ISSUE THREAD

**Issue by jsnel** [glotaran/pyglotaran#777]
Tasks:
- [x] Create a draft PR
- [x] Bring staging up to date with main
- [x] Document changes in PR

- [x] Prepare v0.5 release notes (see PR message in #778)

**Comment by jsnel** [comment]
All done ✔️ here, PR #778 has the green 🟢 light.
