### ISSUE TITLE
🧹 Follow up cleanups for #841

### ISSUE THREAD

**Issue by s-weigand** [glotaran/pyglotaran#855]
Meta issue to keep track of the follow up cleanups for #841

For v0.7.0:
- [x] ♻️ Remove parameter.py from linter exceptions #849
- [ ] ♻️ Rename dataclass_helper functions and arguments with more sensible #853
- [x] 🗑️ Properly deprecate ParameterGroup.to_csv #854
- [x] 🗑️ Deprecate changed scheme file specs #857
- [x] ♻️ Refactor Result and Scheme loading to to use 'file' fields #858

for v1.0.0:
- [ ] ✨♻️ Extend result reconstruction #856
